name: Build Executable for Linux, Windows, and macOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    
    # Use Ubuntu 20.04 for Linux builds
    container: 
      image: ubuntu:20.04
      options: --user root

    steps:
      - name: Install dependencies for Ubuntu 20.04
        if: matrix.os == 'ubuntu-latest'
        run: |
          apt update && apt install -y python3 python3-pip patchelf
          python3 -m pip install --upgrade pip
          pip install  lap numpy ultralytics opencv-python  pytesseract fast_plate_ocr
          pip install pyinstaller

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --name=main_${{ matrix.os }} main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: executable-${{ matrix.os }}
          path: dist/main_${{ matrix.os }}
